### ISSUE TITLE
pact-jvm-consumer-groovy generates incorrect contents in message pact file

### ISSUE THREAD

**Issue by qmg-rbass** [DiUS/pact-jvm#1011]
Version `4.0.2` of `pact-jvm-consumer-groovy` seems to have introduced a bug where the generated message pact file contains incorrect `contents`. Rather than being a JSON object, `contents` is a String representation of the expected JSON.

With this code:

```
def pactMessageBuilder = new PactMessageBuilder().with {
    serviceConsumer 'consumer'
    hasPactWith 'provider'
    expectsToReceive 'feed entry'
    withMetaData(contentType: 'application/json')
    withContent(contentType: 'application/json') {
        type 'foo'
        data {
            reference {
                id string('abc')
            }
        }
    }
}
```

`4.0.2` generates:

```
{
  "consumer": {
    "name": "consumer"
  },
  "provider": {
    "name": "provider"
  },
  "messages": [
    {
      "description": "feed entry",
      "metaData": {
        "contentType": "application/json"
      },
      "contents": "{\n    \"type\": \"foo\",\n    \"data\": {\n        \"reference\": {\n            \"id\": \"abc\"\n        }\n    }\n}",
      "matchingRules": {
        "body": {
          "$.data.reference.id": {
            "matchers": [
              {
                "match": "type"
              }
            ],
            "combine": "AND"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "4.0.2"
    }
  }
}
```

whereas `4.0.1` generates:

```
{
  "consumer": {
    "name": "consumer"
  },
  "provider": {
    "name": "provider"
  },
  "messages": [
    {
      "description": "feed entry",
      "metaData": {
        "contentType": "application/json"
      },
      "contents": {
        "type": "foo",
        "data": {
          "reference": {
            "id": "abc"
          }
        }
      },
      "matchingRules": {
        "body": {
          "$.data.reference.id": {
            "matchers": [
              {
                "match": "type"
              }
            ],
            "combine": "AND"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "4.0.1"
    }
  }
}
```

I have created a repo to reproduce the issue here: https://github.com/qmg-rbass/pact-bug

**Comment by uglyog** [comment]
4.0.6 has been released with this fix

**Comment by qmg-rbass** [comment]
Thank you @uglyog.

I cannot upgrade right now though, because of the upgrade to Groovy 3 in 4.0.6. Shouldn't that have warranted a new major version?

**Comment by uglyog** [comment]
Oh, damn, forgot that module has groovy code in it. I was thinking it is just used for running Spock, so didn't need a version bump.

You can try excluding the Groovy 3 dependency. It may still work with 2.5.

**Comment by qmg-rbass** [comment]
Exclusion doesn't work unfortunately. It's actually the opposite problem - the pact module is expecting Groovy 3 to be on the class path, but we're using Spock `1.3-groovy-2.5`. This is the exception:

```
java.lang.NoClassDefFoundError: org/codehaus/groovy/vmplugin/v8/IndyInterface
	at au.com.dius.pact.consumer.groovy.messaging.PactMessageBuilder.serviceConsumer(PactMessageBuilder.groovy:31)
	at com.___.___(___.groovy:26)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at com.___.___(___.groovy:25)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.vmplugin.v8.IndyInterface
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

I don't really want to upgrade Spock to `2.0-M2-groovy-3.0` right now, given it's only a milestone release.

**Comment by uglyog** [comment]
Ok, I'll set that module back to 2.5

**Comment by uglyog** [comment]
Version 4.0.7 has been released with this change

**Comment by qmg-rbass** [comment]
Working well after upgrade, thanks @uglyog
