### ISSUE TITLE
Spring Boot consumer test no longer works after upgrading to 4.0.0

### ISSUE THREAD

**Issue by tinexw** [DiUS/pact-jvm#949]
I recently tried to upgrade my consumer test (Junit5, Spring Boot 2.1.9) from 3.x to 4.x.  The test fails because the mocked server does not respond. (Neither in the test nor from curl.) It still works in the last beta version `4.0.0-beta.6`.

The issue seems to be caused by a change in this method: `au.com.dius.pact.consumer.BaseJdkMockServer#toPactRequest`

It was changed from 
`
val bodyContents = exchange.requestBody.bufferedReader(calculateCharset(headers)).readText()
`

to 

`
val bodyContents = exchange.requestBody.readBytes()
`

It's not working for me because I have kotlin 1.2.7 and the `readBytes()` does not yet exist in that version. However, this is not obvious because the `java.lang.NoSuchMethodError: kotlin.io.ByteStreamsKt.readBytes(Ljava/io/InputStream;)` exception is  caught by the Server (kinda silently - only logged with trace level) and the connection is closed.

**Comment by tinexw** [comment]
Workaround: Override the 1.2 kotlin version that comes from the spring boot bom:

In `build.gradle`:  `ext['kotlin.version'] = '1.3.50'`

**Comment by ariesmcrae** [comment]
> Workaround: Override the 1.2 kotlin version that comes from the spring boot bom:
> 
> In `build.gradle`: `ext['kotlin.version'] = '1.3.50'`

For the maven folks, ensure it's in 'test' scope if you don't use kotlin directly in your business code.

`
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib</artifactId>
        <version>1.3.60</version>
        <scope>test</scope>
    </dependency>
`
