### ISSUE TITLE
Gradle plugin does not work with Kotlin DSL

### ISSUE THREAD

**Issue by pkubowicz** [DiUS/pact-jvm#852]
Having `build.gradle.kts` like
```
plugins {
    id("au.com.dius.pact") version "3.6.2"
}

pact {
    publish {
        pactBrokerUrl = "http://localhost:80"
    }
}
```
causes an error:

```
Script compilation errors:

  Line 70:     publish {
                       ^ Type mismatch: inferred type is () -> TypeVariable(_L) but Closure<(raw) Any!>! was expected

  Line 71:         pactBrokerUrl = "http://localhost:80"
                   ^ Unresolved reference: pactBrokerUrl

2 errors
```

I guess PactPluginExtension should use org.gradle.api.Action instead of Groovy Closure.

**Comment by pkubowicz** [comment]
I suppose changing the plugin to use
```
    def publish(Action<? extends PactPublish> closure) {
        publish = new PactPublish()
        closure.execute(publish)
    }
```
will fix the issue, but I am not able to verify it: I am not able to publish the plugin locally from pact-jvm repo. Also using Composite Build does not work.

**Comment by uglyog** [comment]
Action is meant for task actions, so it doesn't feel right the right class to use. Probably just need a Java functional interface

**Comment by uglyog** [comment]
I have been playing around with this, and as the way plugins are configured has changed I concerned this may be a bit too big a change for 3.6.x branch. I'll work on a rewrite on the 4.0.x branch.

**Comment by pkubowicz** [comment]
org.gradle.api.Action is used to configure a Gradle object, not for task actions. See https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:task(java.lang.String,%20groovy.lang.Closure) - Action is used to create a sibling method that does not use Groovy classes.

**Comment by borisilic** [comment]
Just wondering if this is possible now? I'm creating a new project with gradle and trying to use kotlin as the DSL but I'm a bit stuck on the top part. Would you recommend just going back to Groovy or are there examples of this setup with Kotlin?

**Comment by uglyog** [comment]
This still needs to be done

**Comment by pkubowicz** [comment]
I have a working prototype, I will submit a pull request.

**Comment by pkubowicz** [comment]
I had problems writing an automated test with Kotlin DSL, so I tested this with a standalone project:
```
plugins {
    id("au.com.dius.pact") version "4.0.2"
}

pact {
    publish {
        pactBrokerUrl = "http://localhost:80"
    }
    reports {
        defaultReports()
    }
    serviceProviders {
        create("provider1") {
            protocol = "http"
        }
    }
}
```
